### ISSUE TITLE
newbie {"GetUserAuthTokenResult":null}

### ISSUE THREAD

**Issue by monigrip** [tuck182/harmony-java-client#15]
I believe the install is correct, however could be wrong.

the Execute the jar line 'HARMONY_HOST LOGITECH_USERNAME LOGITECH_PASSWORD' I've swapped out with IP address and username(email) and password, is this correct?

I have this error.

21:24:59.965 [main] DEBUG n.w.harmony.HarmonyClient - listener[net.whistlingfish.harmony.Main$1@544a2ea6] added
21:25:00.878 [main] DEBUG n.w.harmony.protocol.AuthService - auth token request returned: {"GetUserAuthTokenResult":null}
Exception in thread "main" java.lang.RuntimeException: Failed to parse response from Logitech auth service
	at net.whistlingfish.harmony.protocol.AuthService.getLoginToken(AuthService.java:45)
	at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:111)
	at net.whistlingfish.harmony.Main.execute(Main.java:37)
	at net.whistlingfish.harmony.Main.main(Main.java:27)
Caused by: us.monoid.json.JSONException: JSONObject["GetUserAuthTokenResult"] is not a JSONObject.
	at us.monoid.json.JSONObject.getJSONObject(JSONObject.java:579)
	at net.whistlingfish.harmony.protocol.AuthService.getLoginToken(AuthService.java:41)
	... 3 more

**Comment by bwssytems** [comment]
This should be closed at is resolved with the authentication change.
