### ISSUE TITLE
Can't use Library in Own Application

### ISSUE THREAD

**Issue by neoprogger** [tuck182/harmony-java-client#3]
Hallo,
i tried to use your Library in an own application.
I compiled the src with gradle and added it to my Project.
Simplified Code:
```java
private HarmonyClient client = new HarmonyClient();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        client.addListener(new ActivityChangeListener() {
            @Override
            public void activityStarted(Activity activity) {
                jLabel1.setText("activity changed: " + activity.getLabel());
            }
        });
        client.connect("MyHubsIp", "myharmonyuser", "mypassword");
        jLabel1.setText("Connected");
    }                            
```

But all I get is 
```java
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:96)
	at harmonyjavaapp.MainForm.jButton1ActionPerformed(MainForm.java:80)
```

The HarmonyClient.java:96 corresponds to:

```
         * 16: invokespecial net/whistlingfish/harmony/HarmonyClient.createConnectionConfig:(Ljava/lang/String;I)Lorg/jivesoftware/smack/ConnectionConfiguration;

```
using the built-in shell works!
Any Help?
IDE: NetBeans 8.0.2 on MacOS Yosemite
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Thanks

**Comment by neoprogger** [comment]
Nevermind: client = HarmonyClient.getInstance(); fixed
