### ISSUE TITLE
get_config fails if json data contains String.format specifiers

### ISSUE THREAD

**Issue by tuck182** [tuck182/harmony-java-client#4]
get_config
    java.util.MissingFormatArgumentException: Format specifier '2f'
    at java.util.Formatter.format(Formatter.java:2487)
    at java.util.Formatter.format(Formatter.java:2423)
    at java.lang.String.format(String.java:2790)
    at net.whistlingfish.harmony.shell.ShellCommand.println(ShellCommand.java:12)
    at net.whistlingfish.harmony.shell.GetConfigCommand.execute(GetConfigCommand.java:8)
    at net.whistlingfish.harmony.shell.ShellCommandWrapper.execute(ShellCommandWrapper.java:20)

The simple fix is to stop using String.format for that output or pass the json data in as an arg (should also review uses of the println method to make sure inputs are cleaned up).

**Comment by intrepidsilence** [comment]
This error is still occurring.  Have you had any success in fixing it?

**Comment by intrepidsilence** [comment]
Nevermind. I did a pull and the dev version works.  I guess you just need to do a new release so everyone does not have to install gradle.
