### ISSUE TITLE
 java.lang.NoClassDefFoundError: com/google/inject/Module

### ISSUE THREAD

**Issue by benediktarnold** [tuck182/harmony-java-client#8]
Hi,
I cloned the repo and build it using gradle like described in the readme. But I got a NoClassDefFoundError during start

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/inject/Module
	at net.whistlingfish.harmony.Main.main(Main.java:24)
Caused by: java.lang.ClassNotFoundException: com.google.inject.Module
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by benediktarnold** [comment]
Sorry I've taken the wrong jar ;-)
